---
title: "Hijacked Journal Detection Toolbox"
format:
  html:
    include-after-body:
      - text: |
         <script src=" https://cdn.jsdelivr.net/npm/lodash@4.17.23/lodash.min.js "></script>
      - text: |
         <script src="https://releases.jquery.com/git/jquery-git.min.js"></script>
      - text: |
          <script src="../js/APIcall.js"></script>
      - text: |
         <script src="../js/fileHandling.js"></script>
---

::: {.callout-important appearance="minimal"}
This page displays some unpolished tools meant to help research integrity specialists and other sleuths do a quick spot-check of suspected hijacked journals. While they use the Crossref API to gather metadata about journals, publishers, and individual works, they **are not** a replacement for the API. Please do not try to use this website for large-scale investigations; Crossref has many options for [retrieving metadata](https://www.crossref.org/documentation/retrieve-metadata/) at scale
:::

::: {.callout appearance="minimal"}
Click [here](../projects/projects.qmd#hijacked-journal-detection-toolbox) to learn more about the motivations for this project. If you are a research integrity specialist and have suggestions for how to improve these tools, please reach out to me on bluesky or by email cnsodano@gmail.com

If there are any bugs, let me know and I'll fix them. This is far from a polished product.
:::

Type a journal title search query to search for duplicate journal titles (often signs of hijacking) registered in Crossref's database. The tool will show only up to the first 30 duplicate listings (double click submit to try a different query. May take a while to load). This is not a comprehensive tool. For example, not all journals register DOIs through Crossref. If your query is overly broad ("Science", e.g.) it's possible it will fail to detect due to [technical reasons]{.inline-code}^[Currently I am not using cursors as I expected users to have a particular journal in mind. If none of the first 30 results for the query match exactly, it will not (as of 4/8/25) search the next page of results. This can be easily fixed when I get around to it.]

```{=html}
<form id="queryFormid">
        <input style="width:40vw;" type="text" id="queryInput" placeholder="American Journal of Public Health" value="American Journal of Public Health">
        <button class="btn btn-light" type="button" id="queryInputSubmit" data-bs-toggle="collapse"
        data-bs-target="#collapseExampleGenericJournal" aria-expanded="false" aria-controls="collapseExampleGenericJournal">
        Submit
        </button>
    </form>
    <div class="collapse" id="collapseExampleGenericJournal">
        <div class="card card-body">
        <div class="TablegetJournalGeneric">
            <p class='loadingsign'>Loading...</p>
            <table>
            </table>
        </div>
        </div>
    </div>
    <br>
    <form id="CRdoiForm">
        <div id="DOIinputDiv">
        <label>Input a DOI to find the Crossref Member that Submitted it:</label><br>
        <input type="text"  id="doiinput", placeholder="https://doi.org/10.52783/rlj.v11i5.2651" value ="https://doi.org/10.52783/rlj.v11i5.2651">
        <input id="CRdoiSubmit" class="btn btn-light" type="submit">
    <br>
    <p id="failMemberFind">Failed to find member, either because the query you submitted was not a DOI or had an invalid prefix. To check if the DOI is registered through crossref, try: <code>https://api.crossref.org/works/{doi}/agency</code></p>
    <div style="padding-left:5%">
    <p id="PmemberName">
    </p>  
    <p id="PmemberID"> 
    </p>
    </div>
    </div>

    </form>
    <br>
    <p id="memberIDErrorMsg">
        <label>Input a valid Crossref Member ID to find all the journals it publishes. A maximum of 100 journals will be
        displayed. (may take a few
        seconds to load for high-volume publishers):</label>
        <br>

    <form id="CRapiForm">

        <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="limitNumReturnedJournalsCheckbox">
        <label class="form-check-label" style="margin-left:5%" for="limitNumReturnedJournalsCheckbox">
            Limit number of results for better performance?
        </label>
        
        </div>
        
        
        <input type="text" id="numJournalToLimitToInput" placeholder="10" value="10" style="display:none;">
        <input type="text" id="memberIDinput" placeholder="30593" value="30593" list="memberIDlist">
        <datalist id="memberIDlist">
        <option value="30593"></option>
        <option value="31492"></option>
        <option value="51526"></option>
        </datalist>

        <input type="submit" class="btn btn-light" id="memberIDforJournalsGetSubmit" data-bs-toggle="collapse"
        data-bs-target="#collapsememberIDforJournalsGetSubmit" aria-expanded="false"
        aria-controls="collapsememberIDforJournalsGetSubmit">
    </form>
    <div class="collapse" id="collapsememberIDforJournalsGetSubmit">
        <div class="card card-body">
        <div class="TablememberIDforJournalsGetSubmit">
            <p id="memberIDErrorMsg2" style="display:none;"></p>
            <p class='loadingsign' id="">Loading...this can sometimes take up to 10 seconds or more</p>
            <!-- _todo deal with loading sign on error _later -->
            <table>
            </table>
        </div>
        </div>
    </div>
    </p>
    <label>Input a publisher ID and find all of its registered journals that have already been registered (possible hijacked
        journals):</label>
    <form id="findAllHijackedJournals">
        <input type="text" id="findAllHijackedJournalsInput" placeholder="30593" value="">
        <button id="findAllHijackedJournalsSubmit" class="btn btn-light">Submit</button>
    </form>
```